# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SOPT_iOS_Login' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SOPT_iOS_Login
  pod 'Alamofire'

end
